apiVersion: v1
kind: Service
metadata:
  name: todolist-clusterip-service
spec:
  selector:
    app: todolist # Цей селектор співпадає з міткою на наших подах
  ports:
  - protocol: TCP
    port: 80 # Порт, який сервіс буде відкривати (внутрішній)
    targetPort: 8080 # Порт, на якому слухає контейнер (ваш Django додаток)
  type: ClusterIP
