apiVersion: v1
kind: Pod
metadata:
  name: todolist-pod-1
  labels:
    app: todolist
spec:
  containers:
  - name: todolist-container
    image: leoleiden/todoapp
    ports:
    - containerPort: 8080
    env:
    - name: DJANGO_SETTINGS_MODULE
      value: "todolist.settings"
    - name: PYTHONUNBUFFERED
      value: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: todolist-pod-2
  labels:
    app: todolist
spec:
  containers:
  - name: todolist-container
    image: leoleiden/todoapp
    ports:
    - containerPort: 8080
    env:
    - name: DJANGO_SETTINGS_MODULE
      value: "todolist.settings"
    - name: PYTHONUNBUFFERED
      value: "1"
